// Static list of exactly 100 short motivational quotes
export const MOTIVATIONAL_QUOTES = [
  "Consistency beats talent when talent doesn't work hard.",
  "Your future is created by what you do today, not tomorrow.",
  "Small daily improvements over time lead to stunning results.",
  "It is not about having time, it is about making time.",
  "Don't wish it were easier. Wish you were better.",
  "The only bad workout is the one that didn't happen.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Discipline is choosing between what you want now and what you want most.",
  "Do something today that your future self will thank you for.",
  "The secret of your future is hidden in your daily routine.",
  "You don't have to be perfect; you just have to be consistent.",
  "Streaks are built one single day at a time.",
  "Focus on the process, and the results will take care of themselves.",
  "Only you can change your life. No one can do it for you.",
  "Energy flows where attention goes.",
  "Habits are the compound interest of self-improvement.",
  "You get what you repeat.",
  "The best way to predict your future is to create it.",
  "What we do repeatedly defines who we are.",
  "Start where you are. Use what you have. Do what you can.",
  "Continuous improvement is better than delayed perfection.",
  "Every action you take is a vote for the person you wish to become.",
  "Change is hard at first, messy in the middle, and gorgeous at the end.",
  "Look in the mirror. That's your competition.",
  "The pain of discipline is nothing compared to the pain of regret.",
  "Show up, show up, show up, and after a while, the showing up becomes a habit.",
  "Make it a habit, make it a lifestyle.",
  "You are one decision away from a completely different life.",
  "Motivation gets you started. Habit keeps you going.",
  "Believe you can and you're halfway there.",
  "Success is not final; failure is not fatal: It is the courage to continue that counts.",
  "Great things are done by a series of small things brought together.",
  "If you want to fly, give up everything that weighs you down.",
  "Dream big. Start small. Act now.",
  "It always seems impossible until it's done.",
  "Your habits will determine your future.",
  "Success is a journey, not a destination.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do it for yourself, not for anyone else.",
  "You don't need a new year to make a change. All you need is today.",
  "Be stronger than your excuses.",
  "Rome wasn't built in a day, but they were laying bricks every hour.",
  "The difference between who you are and who you want to be is what you do.",
  "Little by little, day by day, what is meant for you will find its way.",
  "Your body can stand almost anything. It's your mind that you have to convince.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "A year from now you may wish you had started today.",
  "Never ruin a good today because of a bad yesterday.",
  "Focus on the step in front of you, not the whole staircase.",
  "You are capable of amazing things.",
  "Push yourself because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The key to success is to focus on goals, not obstacles.",
  "Work hard in silence, let your success be your noise.",
  "Don't decrease the goal. Increase the effort.",
  "Difficult roads often lead to beautiful destinations.",
  "If it doesn't challenge you, it won't change you.",
  "A habit cannot be tossed out the window; it must be coaxed down the stairs.",
  "An investment in yourself pays the best interest.",
  "The successful warrior is the average man, with laser-like focus.",
  "Small habits don't add up. They compound.",
  "It is easier to prevent bad habits than to break them.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "Be the change that you wish to see in the world.",
  "Be patient with yourself. Self-growth is tender; it's holy ground.",
  "Your life is the fruit of your decisions.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Act as if what you do makes a difference. It does.",
  "Strive for progress, not perfection.",
  "You miss 100% of the shots you don't take.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "The track of a runner is marked by sweat, not wishes.",
  "It's never too late to be what you might have been.",
  "You are never too old to set another goal or to dream a new dream.",
  "The power of habit is supreme.",
  "Action is the foundational key to all success.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Build habits today that create freedom tomorrow.",
  "Slow and steady wins the race.",
  "The secret to getting ahead is getting started.",
  "A journey of a thousand miles begins with a single step.",
  "Do not let what you cannot do interfere with what you can do.",
  "The best preparation for tomorrow is doing your best today.",
  "Out of difficulties grow miracles.",
  "Hard work beats luck, always.",
  "Nothing will work unless you do.",
  "Make each day your masterpiece.",
  "The only way to do great work is to love what you do.",
  "You must do the things you think you cannot do.",
  "Your life does not get better by chance, it gets better by change.",
  "If you can dream it, you can do it.",
  "Keep moving forward.",
  "The main thing is to keep the main thing the main thing."
];

// Seeded deterministic hash to pick daily quote
function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  return Math.abs(hash);
}

export function getDailyQuote(dateStr: string): string {
  const hash = hashString(dateStr);
  const index = hash % MOTIVATIONAL_QUOTES.length;
  return MOTIVATIONAL_QUOTES[index];
}
